server:
  port: 0

spring:
  application:
    name: app-test
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:base-${spring.profiles.active}.yml
      - nacos:base-db-${spring.profiles.active}.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
