spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: app-test
              uri: lb://app-test
              predicates:
                - Path=/test/**
              filters:
                - StripPrefix=1
  cache:
    type: caffeine

logging:
  level:
    root: info
    com:
      drx: debug
