spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 3s
      timeout: 5s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 1
          max-wait: 3s
