server:
  port: 9090

spring:
  application:
    name: app-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
