spring:
  data:
    redis:
      host: dr-x.top
      port: 6379
      password: 123qqq...A
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          max-wait: 1000ms
